language: node_js

node_js:
  - stable

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq google-cloud-sdk
  - gcloud components install cloud-datastore-emulator

install:
  - npm install

script:
  - npm run test:ci

before_script:
  - gcloud beta emulators datastore start &
  - $(gcloud beta emulators datastore env-init)
