language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run test:ci

dist: trusty
  apt:
    packages:
    - google-cloud-sdk
before_script:
- gcloud beta emulators datastore start &
- $(gcloud beta emulators datastore env-init)
